### ISSUE TITLE
Build a new image

### ISSUE THREAD

**Issue by jayminkapish** [oliver006/drone-cloud-run#6]
Can we please release a new `latest` tag to pick up the latest version of gcloud SDK?

The current `latest` tagged image is using Google Cloud SDK 261.0.0 and is very behind from the current stable version https://cloud.google.com/sdk/docs/release-notes.

I learned about this after a few days of troubleshooting following error:

```
Deploying new service...
failed
Deployment failed
ERROR: (gcloud.beta.run.deploy) INVALID_ARGUMENT: Invalid JSON payload received. Unknown name "initializers" at 'service.metadata': Cannot find field.
Invalid JSON payload received. Unknown name "initializers" at 'service.spec.run_latest.configuration.revision_template.metadata': Cannot find field.
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: "Invalid JSON payload received. Unknown name \"initializers\" at\
      \ 'service.metadata': Cannot find field."
    field: service.metadata
  - description: "Invalid JSON payload received. Unknown name \"initializers\" at\
      \ 'service.spec.run_latest.configuration.revision_template.metadata': Cannot\
      \ find field."
    field: service.spec.run_latest.configuration.revision_template.metadata
2021/01/22 16:06:16 runConfig() err: error: exit status 1
```

**Comment by oliver006** [comment]
Tagged [v0.0.2](https://github.com/oliver006/drone-cloud-run/releases/tag/v0.0.2) and published a [new docker image](https://hub.docker.com/layers/oliver006/drone-cloud-run/v0.0.2/images/sha256-342115290b95b9ee9c91a288908bd569df8f2bd4205e75792ab552028c8eab54?context=explore).
