### ISSUE TITLE
Drop `beta` from `gcloud beta run deploy`

### ISSUE THREAD

**Issue by jayminkapish** [oliver006/drone-cloud-run#7]
https://github.com/oliver006/drone-cloud-run/blob/master/main.go#L138

It is now GA. https://cloud.google.com/sdk/gcloud/reference/run/deploy

**Comment by oliver006** [comment]
Closed by https://github.com/oliver006/drone-cloud-run/commit/2122c05a1184bb83be458343b2e7ce4dafb826bb
