### ISSUE TITLE
Support deploys to multiple regions?

### ISSUE THREAD

**Issue by abstrctn** [oliver006/drone-cloud-run#8]
One pattern we're using and seems like it could be common is to deploy a service to multiple regions for geographic redundancy. A way to make this more concise in drone configs would be to accept an array of regions to deploy to. But I'm not sure whether drone conventions are opinionated about 2+ "things" happening within a single step. (If it discourages that, then ignore this...)

I could see someone implementing this either by increasing options to this plugin, or by having cloned steps running for each region in parallel.

Some Pros to changing the plugin that I see:
* More concise `drone.yaml` without needing to use dynamically generated config
* Could support features like rolling back all regions if a deploy to any one fails (and no need for user to ever implement this alone)

But of course some pros to keeping that logic out of the plugin:
* Less complex plugin (always good)
* More default flexibility for users to decide on order/parallelism/rollback rules

**Comment by oliver006** [comment]
I think you could leverage jsonette or yaml anchors if your drone files get too verbose.

If you want to do more complex operations (like deploys to multiple regions and rollback in case of partial failures) as par of your deploys then the plugin is probably not the right place for that. You can always script something by calling the `gcloud` command directly.

**Comment by abstrctn** [comment]
Makes sense to me! YAML anchors seem like they would cover most cases, I'll close this.
