### ISSUE TITLE
Support alpha / beta gcloud options via settings

### ISSUE THREAD

**Issue by abstrctn** [oliver006/drone-cloud-run#9]
I know we did this to ourselves by asking to change the gcloud command from `beta` to general availability (#7 - which is still probably a good default), but we have a new need now for the `--tag` argument during deploys, which is only available on the alpha/beta release tracks.

Wondering if it would make sense to make this configurable a setting, like `track` / `release_track`, or even just adding `alpha` or `beta` flags as options. Since features tend to stay in the alpha/beta tracks for many months, I think it could be worthwhile to preserve the ability to use them.

**Comment by oliver006** [comment]
I think adding a flag for `beta` makes sense.
I'm short of time right now but if you submit a PR I'd be happy to review and merge it.

**Comment by jayminkapish** [comment]
@oliver006, can you add us both as collaborators to this repo?

**Comment by oliver006** [comment]
@jayminkapish - let's stick with the tried and true approach of PRs for now, I have no problems reviewing and merging them. We can revisit that in the future if you feel like that's a problem.

**Comment by jayminkapish** [comment]
sounds good. We've suggested a change to accommodate this in a PR.

**Comment by oliver006** [comment]
Released as [v0.0.3](https://github.com/oliver006/drone-cloud-run/releases/tag/v0.0.3)
